name: Go

on:
  push:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        HOST_OS=linux make && mv bin bin_linux
        HOST_OS=windows make && mv bin bin_windows
        HOST_OS=darwin make && mv bin bin_darwin
        HOST_OS=freebsd make && mv bin bin_freebsd

    - name: Upload Linux Build
      uses: actions/upload-artifact@v2
      with:
        name: freya-linux
        path: ./bin_linux

    - name: Upload Windows Build
      uses: actions/upload-artifact@v2
      with:
        name: freya-windows
        path: ./bin_windows

    - name: Upload macOS Build
      uses: actions/upload-artifact@v2
      with:
        name: freya-darwin
        path: ./bin_darwin

    - name: Upload FreeBSD Build
      uses: actions/upload-artifact@v2
      with:
        name: freya-freebsd
        path: ./bin_freebsd
